---
title: Unix tijdstempels
hero_image: images/banner.png
description: Unix tijdstempels begrijpen
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - title: Unix tijdstempels
