title: Unix timestamps
hero_image: images/banner.png
description: Understanding Unix timestamps
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
interests: ""
technologies: ""
steps:
  - title: Unix timestamps
