---
title: Timestamps Unix
hero_image: images/banner.png
description: Entendendo os timestamps Unix
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - 
    title: Timestamps Unix
