---
title: Unix vremenske oznake
hero_image: images/banner.png
description: Razumijevanje vremenskih oznaka Unixa
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - title: Unix vremenske oznake
