---
title: Horário Unix
hero_image: images/banner.png
description: Entendendo o horário Unix
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - 
    title: Horário Unix
