---
title: Unixowe znaczniki czasu
hero_image: images/banner.png
description: Zrozumienie Unixowych znaczników czasu
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - 
    title: Unixowe znaczniki czasu
